// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DeliveryApp
{
	public partial class HomeViewController : UIViewController
	{
		public HomeViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
