// This file has been autogenerated from a class added in the UI designer.

using System;
using DeliveryApp.Models;
using Foundation;
using UIKit;

namespace DeliveryApp
{
	public partial class RegisterViewController : UIViewController
	{
       // public string emailAddress { get; set; } 

        public RegisterViewController (IntPtr handle) : base (handle)
		{

           // registerButton.TouchUpInside += RegisterButton_TouchUpInside;
		}

       /* private async void RegisterButton_TouchUpInside(object sender, EventArgs e)
        {
            string email = emailTextFIeld.Text;
            string password = passwordTextField.Text;
            string confirmPassword = password;

            if (string.IsNullOrEmpty(email) && string.IsNullOrEmpty(password))
            {

                if (password == confirmPassword)
                {
                    var user = new Users()
                    {
                        Email = email,
                        Password = password
                    };

                    int row = await AppDelegate.connect.InsertAsync(user);

                    if (row > 0)
                    {
                        var alert = UIAlertController.Create("Success", "User Inserted", UIAlertControllerStyle.Alert);

                        alert.AddAction(UIAlertAction.Create("Ok", UIAlertActionStyle.Default,null));

                        PresentViewController(alert, true, null);



                    }else
                    {
                        var alert = UIAlertController.Create("Failed", "User Not Inserted", UIAlertControllerStyle.Alert);

                        alert.AddAction(UIAlertAction.Create("Ok", UIAlertActionStyle.Destructive, null));

                        PresentViewController(alert, true, null);
                    }

                }

            }
        }

        
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            emailTextFIeld.Text = emailAddress;






        } */


      
    }
}
