// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using DeliveryApp.iOS.Models;
using Foundation;
using UIKit;

namespace DeliveryApp.iOS
{
	public partial class DeliveriesViewController : UITableViewController
	{

		List<Delivery> deliveries; 


		public DeliveriesViewController (IntPtr handle) : base (handle)
		{
            deliveries = new List<Delivery>();
		}


        public override async void ViewDidLoad()
        {
            base.ViewDidLoad();

			deliveries = await Delivery.GetDeliveries();
            TableView.ReloadData();
        }


        public override nint RowsInSection(UITableView tableView, nint section)
        {
            return deliveries.Count;
        }


        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {

            var cell = tableView.DequeueReusableCell("deliveryCell") as DeliveryTableViewCell;

            var delivery = deliveries[indexPath.Row];

            cell.NameLabel.Text = delivery.Name;

            cell.CoordinateLabel.Text = $"{delivery.DestinationLatitude:0}, {delivery.DestinationLongitude:0}";
            switch (delivery.Status)
            {
                case 0:
                    cell.StatusLabel.Text = "waiting Delivery Person";

                    break;
                case 1:

                    cell.StatusLabel.Text = "In Delivery";
                    break;

                case 2:
                    cell.StatusLabel.Text = "Delivered";

                    break;

               
                default:
                    break;
            }

            return cell;
        }

       /* [Export("tableView:heightForRowAtIndexPath:")]
        public override nfloat GetHeightForRow(UITableView tableView, NSIndexPath indexPath)
        {
            throw new System.NotImplementedException();
        }
       */
    }
}
