// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using DeliveryApp.iOS.Models;
using Foundation;
using UIKit;

namespace DeliveryApp.iOS
{
	public partial class DeliveredViewController : UITableViewController
	{

		List<Delivery> delivered; 
		public DeliveredViewController (IntPtr handle) : base (handle)
		{
            delivered = new List<Delivery>();
		}

        public async override void ViewDidLoad()
        {
            base.ViewDidLoad();

			delivered = await Delivery.GetDelivered();

            TableView.ReloadData(); 
        }


        public override nint RowsInSection(UITableView tableView, nint section)
        {
            return delivered.Count;
        }


        public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            var cell = tableView.DequeueReusableCell("deliveredCell") as DeliveredTableViewCell;

            var deliveredValue = delivered[indexPath.Row];




            cell.NameLabel.Text = deliveredValue.Name;

            cell.CoordinateLabel.Text = $"{deliveredValue.DestinationLatitude},{deliveredValue.DestinationLongitude}";

            switch (deliveredValue.Status)
            {
                case 0:
                    cell.StatusLabel.Text = "waiting Delivery Person";

                    break;
                case 1:

                    cell.StatusLabel.Text= "In Delivery";
                    break;

                case 2:
                    cell.StatusLabel.Text = "Delivered";

                    break;


                default:
                    break;
            }

            return cell;
        }

       /* [Export("tableView:heightForRowAtIndexPath:")]
        public override  nfloat GetHeightForRow(UITableView tableView, NSIndexPath indexPath)
        {
            throw new System.NotImplementedException();
        }
       */
    }


}
