// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DeliveryApp.iOS
{
	public partial class MainTabBarController : UITabBarController
	{
		public MainTabBarController (IntPtr handle) : base (handle)
		{
		}



        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);
            NavigationItem.SetHidesBackButton(true,false);


        }
    }
}
