// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreLocation;
using DeliveryApp.iOS.Models;
using Foundation;
using MapKit;
using UIKit;

namespace DeliveryApp.iOS
{
	public partial class NewDeliveryViewController : UIViewController
	{

        CLLocationManager locationManager;

		public NewDeliveryViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            locationManager = new CLLocationManager();

            locationManager.RequestWhenInUseAuthorization();

            OriginMapVIew.ShowsUserLocation = true;
            DestinationMapView.ShowsUserLocation = true;

            OriginMapVIew.DidUpdateUserLocation += OriginMapVIew_DidUpdateUserLocation;
            DestinationMapView.DidUpdateUserLocation += DestinationMapView_DidUpdateUserLocation;
            saveBarButton.Clicked += SaveBarButton_Clicked;
        }

        private void DestinationMapView_DidUpdateUserLocation(object sender, MapKit.MKUserLocationEventArgs e)
        {
           if(DestinationMapView.UserLocation != null)
            {
                var coordinates = OriginMapVIew.UserLocation.Coordinate;

                var span = new MKCoordinateSpan(0.15, 0.15);

                DestinationMapView.Region = new MKCoordinateRegion(coordinates, span);

                DestinationMapView.RemoveAnnotations();

                DestinationMapView.AddAnnotation(new MKPointAnnotation()
                {
                    Coordinate = coordinates,
                    Title = "Your Location"

                });
            }
        }

        private void OriginMapVIew_DidUpdateUserLocation(object sender, MapKit.MKUserLocationEventArgs e)
        {
            if(OriginMapVIew.UserLocation != null)
            {
                var coordinates = OriginMapVIew.UserLocation.Coordinate;
                var span = new MKCoordinateSpan(0.15, 0.15);

                OriginMapVIew.Region = new MKCoordinateRegion(coordinates, span);

                OriginMapVIew.RemoveAnnotations();

                OriginMapVIew.AddAnnotation(new MKPointAnnotation()
                {
                    Coordinate = coordinates,
                    Title = "Your Location"

                });
            }
        }

        private async void SaveBarButton_Clicked(object sender, EventArgs e)
        {

            var origin = OriginMapVIew.CenterCoordinate;

            var destination = DestinationMapView.CenterCoordinate;

            Delivery delivery = new Delivery()
            {
                Name = packageNameTextField.Text,
                Status = 0,
                OriginLatitude = origin.Latitude,
                OriginLongitude = origin.Longitude,
                DestinationLatitude = destination.Latitude,
                DestinationLongitude = destination.Longitude

            };

           int row = await  AppDelegate.connect.InsertAsync(delivery);

            if (row > 0)
            {
                var alert = UIAlertController.Create("Success", "Package Added", UIAlertControllerStyle.Alert);

                alert.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));
                PresentViewController(alert, true, null);
            }
            else
            {
                var alert = UIAlertController.Create("Failed", "Package  not inserted", UIAlertControllerStyle.Alert);

                alert.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Default, null));
                PresentViewController(alert, true, null);
            }

        }
    }
}
