// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DeliveryApp.iOS
{
	public partial class ProfilesVIewController : UIViewController
	{
		public ProfilesVIewController (IntPtr handle) : base (handle)
		{
		}
	}
}
