// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DeliveryPersonApp.iOS
{
	public partial class TabsViewController : UITabBarController
	{
		public TabsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
