// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DeliveryPersonApp.iOS
{
	public partial class WaitingTableViewController : UITableViewController
	{
		public WaitingTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
